### ISSUE TITLE
Generating Class Documentation does not work using PCT version 208 and OE 11.6

### ISSUE THREAD

**Issue by Ton-Pe** [Riverside-Software/pct#239]
I updated PCT into latest version 208 and now generation of class documentation fails with error:
```
BUILD FAILED
c:\enterprise\product\trunk\Tools\build_documentation.xml:124: java.lang.NoClassDefFoundError: com/openedge/pdt/core/ast/EnumeratorItem
at eu.rssw.pct.oedoc.OpenEdgeDocumentation115.execute(OpenEdgeDocumentation115.java:147)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
```

I have OE 11.6.3. In this first attempt I had ast.jar and ast-dependencies.jar  from 11.6.2 because I had forgotten to change those. Then I took ast.jar and ast-dependencies.jar from OE 11.6.3 and tried again. Generating documentation still fails, but with different error:

```
BUILD FAILED
c:\enterprise\product\trunk\Tools\build_documentation.xml:124: java.lang.NullPointerException
at eu.rssw.pct.oedoc.ClassDocumentationVisitor.visit(ClassDocumentationVisitor.java:131)
at com.openedge.pdt.core.ast.TemptableDeclaration.accept(TemptableDeclaration.java:58)
at com.openedge.pdt.core.ast.ASTNode.acceptChildren(ASTNode.java:330)
at com.openedge.pdt.core.ast.TypeDeclaration.accept(TypeDeclaration.java:38)
at com.openedge.pdt.core.ast.ASTNode.acceptChildren(ASTNode.java:330)
at com.openedge.pdt.core.ast.internal.CompilationUnit.accept(CompilationUnit.java:130)
at eu.rssw.pct.oedoc.OpenEdgeDocumentation115.execute(OpenEdgeDocumentation115.java:149)
```

Our partner uses OE 11.7 and says this is working on 11.7. I cannot test this on OE 11.7.

I have included full error messages:
[Error_ast_from_1162.txt](https://github.com/Riverside-Software/pct/files/986201/Error_ast_from_1162.txt)
[Error_ast_from_1163.txt](https://github.com/Riverside-Software/pct/files/986202/Error_ast_from_1163.txt)

**Comment by gquerret** [comment]
I don't want to redistribute the OpenEdge JAR files directly in PCT, but you can still download them:
* https://github.com/Riverside-Software/pct/raw/master/lib/ast.jar
* https://github.com/Riverside-Software/pct/raw/master/lib/ast-dependencies.jar

Documentation has to be updated though...

**Comment by Ton-Pe** [comment]
Unfortunately that did not help. I took those but I am still getting the same error:
```
[echo] Generating XML Class Documentation
[ClassDocumentation] Generating XML documentation (11.5+ method)

BUILD FAILED
c:\enterprise\product\trunk\Tools\build_documentation.xml:123: java.lang.NullPointerException
        at eu.rssw.pct.oedoc.ClassDocumentationVisitor.visit(ClassDocumentationVisitor.java:131)
        at com.openedge.pdt.core.ast.TemptableDeclaration.accept(TemptableDeclaration.java:58)
        at com.openedge.pdt.core.ast.ASTNode.acceptChildren(ASTNode.java:330)
        at com.openedge.pdt.core.ast.TypeDeclaration.accept(TypeDeclaration.java:38)
        at com.openedge.pdt.core.ast.ASTNode.acceptChildren(ASTNode.java:330)
        at com.openedge.pdt.core.ast.internal.CompilationUnit.accept(CompilationUnit.java:130)
        at eu.rssw.pct.oedoc.OpenEdgeDocumentation115.execute(OpenEdgeDocumentation115.java:149)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

I don't know it is relevant, but those jar-files were exactly same size than those I have in 11.6.3.
If I change back to PCT 207 things work.

**Comment by gquerret** [comment]
Found where it comes from; do you know how to rebuild PCT by yourself ?

**Comment by Ton-Pe** [comment]
No. Well, I found instructions on FAQ, but I have never built that by myself. I'm not so familiar with GitHub either.

**Comment by gquerret** [comment]
It seems Mike will be able to send it to you.

**Comment by Ton-Pe** [comment]
Great, thanks!

**Comment by gquerret** [comment]
How does this version work ?

**Comment by Ton-Pe** [comment]
It seems that this version works. At least I'm not getting the Java.Lang.NullPointerException anymore. I still get errors when generating documentation, but I think those are not PCT related errors anymore. I need to discuss with Mike about that.
